### ISSUE TITLE
기업상세 (기업개황) 스크린 UI 구현

### ISSUE THREAD

**Issue by ChiwanAhn** [ChiwanAhn/open_dart#10]
**Expected result**
![image](https://user-images.githubusercontent.com/25087511/88642814-f3a79100-d08e-11ea-8429-3d9fde97603f.png)

**What to do**
1. screens/corporation_detail_screen.dart 파일에 CorporationDetailScreen 을 생성합니다
2. 제시된 이미지를 Widget으로 구현합니다
3. 홈페이지와 IR 홈페이지의 텍스트는 maxLine을 1로 설정합니다

하드코딩된 데이터를 사용해도 무방합니다
아이콘은 이미 Flutter에 포함되어있는 아이콘을 사용해 주세요
아직 플로우가 설계되어있지 않아 스크린연결을 따로 하지는 않으셔도 됩니다
(테스트를 위해 연결하셔도 좋습니다)

완료된 UI를 캡쳐해서 올려주세요

Day3 에 PR을 부탁드립니다

**Comment by kcy0142** [comment]
![dart_mission](https://user-images.githubusercontent.com/1396463/88785431-23a87e80-d1cc-11ea-8c08-8fd5b12a7ad1.PNG)

**Comment by ChiwanAhn** [comment]
@kcy0142 이미 PR이 완료되었는데 이슈 클로징이 늦었네요 ㅠㅠ
다른 분이 올리신 코드와 비교해보셔도 좋을 것 같습니다
올려주셔서 너무나 감사합니다 😊
