### ISSUE TITLE
공시서류원본파일 API xml encoding 이슈

### ISSUE THREAD

**Issue by ChiwanAhn** [ChiwanAhn/open_dart#2]
**Describe the bug**
인코딩 이슈로 받은 데이터의 글자가 깨져서 나옵니다

**To Reproduce**
1. fetch data from URL 
```
curl 'https://opendart.fss.or.kr/api/document.xml?crtfc_key=<API_KEY>&rcept_no=20200724900679' > temp.zip
```
2. unzip with utf-8 encoding 
```
unar -e utf-8 temp.zip
```

**Screenshots**
![image](https://user-images.githubusercontent.com/25087511/88506604-48241100-cfa8-11ea-81bc-754066539008.png)

**Comment by ChiwanAhn** [comment]
API doc 참고 링크 공유드립니다
[https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS001&apiId=2019003]

**Comment by Aqudi** [comment]
API doc가 잘못되어 있었네요.

**Comment by ChiwanAhn** [comment]
![image](https://user-images.githubusercontent.com/25087511/88507572-b79b0000-cfaa-11ea-9adf-9abd1f7bb18c.png)

API 문서에서 UTF-8이라고 표현되어있지만 사실 EUC-KR 파일입니다

따라서 editor의 인코딩을 변경하시면 제대로 볼 수 있습니다
