### ISSUE TITLE
CorpClassChip 에 표현되는 컬러와 데이터 포맷 변경

### ISSUE THREAD

**Issue by ChiwanAhn** [ChiwanAhn/open_dart#3]
**Expected result**
![image](https://user-images.githubusercontent.com/25087511/88508257-596f1c80-cfac-11ea-95a0-3aa364b6eea7.png)

**What to do**
1. 기업유형(corp_cls)에 사용되는 컬러변경
2.`Y 유가` 에서 -> `유가`로 각각 chip에 표현되는 알파벳 제거
3. 위젯의 파일명을 corporation_chip.dart -> corp_class_chip.dart 로 변경

[디자인 파일 참고](https://www.figma.com/file/8WOY4U9YYSEL148TR23ASg/%EB%8B%A4%ED%8A%B8-%EA%B8%B0%EC%97%85%EC%A0%95%EB%B3%B4-%EA%B2%80%EC%83%89-%EA%B5%AC%EB%8F%85-%EC%84%9C%EB%B9%84%EC%8A%A4?node-id=0%3A1)

**Comment by heejoongs** [comment]
@ChiwanAhn PR요청(테스트)
