### ISSUE TITLE
기업개황 API method 생성

### ISSUE THREAD

**Issue by ChiwanAhn** [ChiwanAhn/open_dart#8]
**Expected result**
CorporationDetail 모델로 변환된 데이터

**What to do**
1. dart_open_api_service.dart 파일에 getCorporationDetail method를 추가합니다
2. 요청 인자에 필수값을 param 으로 설정합니다
3. 받아온 데이터를 기업개황 모델로 deserialize합니다

[API 참고 URL](https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS001&apiId=2019002)
endpoint: https://opendart.fss.or.kr/api/company.json

method 가 잘 작동하는지 corp_code를 하드코딩으로 넣으셔서 테스트 해보셔도 좋습니다
**응답결과 json을 남겨주세요**

**Comment by soohoin** [comment]
요청 인자에 필수값이라고 하면... 어떤말일까요??

음... 제가 만들어야 되는 method 가 
어떤일을 하는지 어떤 param을 받는지가 궁금합니다.

기존에 있는 searchCorporations() 는 Future 를 이용해서 데이터를 받아 오고 해당 데이터를 deserialize 하는걸로 이해가 됩니다.

글머 제가 이해한 대로 적어보면
1. searchCorporations() 와 같이 deserialize 를 하는 method 를 만든다.
2. model 은 getCorporationDetail 을 가지고 deserialize 하면된다.
3. 우선 테스트는 로컬에서 Json 데이터 생성 후 해당 Json 데이터를 pram 으로 받아서 수행한다.

위의 1,2,3 번으로 생각하면 되는걸까요??

제가... ㅎㅎ 이해력이 좋지않아서... 죄송합니다~!!

**Comment by ChiwanAhn** [comment]
넵 :) 적어주신대로 진행해 주셔도 좋습니다

기존 searchCorporation 을 참고하셔서 기업개황 API를 이용할 수 있는 method를 동일하게 생성하신다고 보시면 될 것 같습니다
다만 corp_code (기업의 코드)를 입력해야 결과를 얻을 수 있으니 해당 param이 필수로 들어갈 수 있도록 설정해 주시면 좋을것 같습니다

감사합니다

**Comment by soohoin** [comment]
치완님 처음 써주신 카드를 제가 잘못이해하고 있었네요~!
너무도 친절하게 api 까지 알려주셨는데 ㅎㅎ... 
데이터는 현재 카드가 10번 만들어지는데  해당 corparation 안에있는 corp_code 를 가져와서 print 해놨습니다. 

회사 핑계로 너무 늦게 올린 것 같네요! 

결과중 하나를 첨부합니다!! 

{status: 000, message: 정상, corp_code: 00326999, corp_name: 플러스자산운용(주), corp_name_eng: Plus Asset Management Co,. Ltd., stock_name: 플러스자산운용, stock_code: , ceo_nm: 백운성, corp_cls: E, jurir_no: 1101111856298, bizr_no: 2118696513, adres: 서울특별시 영등포구 국제금융로 10 36층(Three IFC)(여의도동, 서울국제금융센터), hm_url: www.plusasset.com, ir_url: , phn_no: 02-3787-2700, fax_no: 02-3787-2795, induty_code: 64201, est_dt: 20000119, acc_mt: 12}
